version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=<Personal-mongodb_url>
      - JWT_SECRET=IwillNotMakeLastAttempt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VITE_API_KEY=<Personal-VITE_API_KEY>
